### ISSUE TITLE
Patient-level export

### ISSUE THREAD

**Issue by tarunkumar985** [smart-on-fhir/bdt#1]
The test server gives message "This server does not require authorization". could you please help me , how the test server comes to the conclusion.

if you could help me which endpoint it is looking for.

Thanks
![image](https://user-images.githubusercontent.com/42908566/73125615-bcb4cd80-3fce-11ea-9abe-f51ffe1c5768.png)

**Comment by vlad-ignatov** [comment]
Hi @tarunkumar985 ,

This is detected from the configuration. Depending on how you use this, there are two ways to change that configuration:
1. Manually, by editing the config.js file and setting `patientExportEndpoint` to "/Patient/$export"` if your server supports it.
2. Using the UI configuration dialog 
    
![Screenshot_20200701_152528](https://user-images.githubusercontent.com/1119082/86283568-4f295080-bbaf-11ea-81d7-e47d21dd2bef.png)
